---
version: "3.5"
services:
  postfix:
    image: docker-postfix
    build:
      context: .
      dockerfile: Dockerfile
    env_file: env
    networks:
      - mail
    ports:
      - "2525:25"
networks:
  mail:
    name: mail
